testsite/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static
from users.views import on_game, model_calculate, champNametoImage, on_game20, model_calculate20
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('post.urls')),
    path('auth/', include("users.urls")),
    # path('', include("writing.urls"))
    path('content/', on_game.as_view()),
    path('model/', model_calculate.as_view()),
    path('convert/', champNametoImage.as_view())
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('', views.main, name = "main"),
    path("login", views.login_view, name = "login"),
    path("logout", views.logout_view, name = "logout"),
    path("signup", views.signup_view, name = "signup"),
    path("index", views.index, name = "index"),
    path("post", views.post, name = "post"),
    path('post/<int:id>', views.detail, name='detail'),
    path("post/edit/<int:id>", views.edit, name = 'edit'),
    path("post/delete/<int:id>", views.delete, name = 'delete'),
]

users/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    student_id = models.CharField(max_length = 10)
    # profile_img = models.ImageField(null = True)

class Board(models.Model):
    # author = models.CharField(max_length=10, null=False)
    author = models.ForeignKey("users.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null = False)
    content = models.TextField(null = False)
    created_date = models.DateTimeField(auto_now_add = True)
    modified_date = models.DateTimeField(auto_now_add = True)
    

users/views.py
from http.client import HTTPResponse
import imp
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from .models import User
from django.urls import reverse
from .models import *
from django.http import HttpResponseRedirect,  Http404
from django.views.decorators.csrf import csrf_exempt
from testsite.on_game_data import ingameOPGG
from testsite.on_game_data20 import getGameData20
from rest_framework.views import APIView
from rest_framework.response import Response
from .evaluation import calculate
from .imageconverter import convert
from .evaluation20 import calculate20
import time

# Create your views here.

class model_calculate(APIView):
    def post(self, request):
        print("reach here1")
        data = request.data.get('champlist')
        # print(data.split(','))
        win_rate = calculate(data.split(','))
        print(win_rate)
        return Response(status=200, data=win_rate)

class model_calculate20(APIView):
    def post(self, request):
        print("reach here1")
        data_champ = request.data.get('champlist')
        data_winrate = request.data.get('winrate')
        print(data_champ)
        print(data_winrate)
        # print(data.split(','))
        win_rate = calculate20(data_champ.split(','), data_winrate.split(','))
        return Response(status=200, data=win_rate)


class champNametoImage(APIView):
    def post(self, request):
        print("reach here1")
        data = request.data.get('champlist')
        imagelist = convert(data.split(','))
        print(imagelist)
        return Response(status=200, data=imagelist)



class on_game(APIView):
    def post(self, request):
        userId = request.data.get('userId')
        # renewalOPGG(userId)
        userOnGameData = ingameOPGG(userId)
        print(userOnGameData)
        idlist = []
        champlist = []

        if (len(userOnGameData['Names']) == 0):
            print("게임중이 아닙니다")
            return Response(status=404)
        else:
            idlist = userOnGameData['Names']
            champlist = userOnGameData['Champions']
            imgList = userOnGameData['Champion Images']
            print(idlist)
            print(champlist)
            return Response(status=200, data=[idlist, champlist, imgList])

class on_game20(APIView):
    def post(self, request):
        userId = request.data.get('userId')
        # renewalOPGG(userId)
        print("on_game20 start")
        userOnGameData = getGameData20(userId)
        time.sleep(7)
        print("getGameDate20 finished")
        print(userOnGameData)
        idlist = []
        champlist = []

        if (len(userOnGameData['Names']) == 0):
            print("게임중이 아닙니다")
            return Response(status=404)
        else:
            idlist = userOnGameData['Names']
            champlist = userOnGameData['Champions']
            imgList = userOnGameData['Champion Images']
            winrate = userOnGameData['Winrate']
            print(idlist)
            print(champlist)
            return Response(status=200, data=[idlist, champlist, imgList, winrate])

def main(request):
    user_id = request.session.get('user')
    print("hello")
    if user_id:
        print("hello1")
        member = User.objects.get(pk = user_id)
        # member_data = {}
        # member_data['login'] = member
        print("hello3434")
        # print(member_data)
        return render(request, "users/main.html", {'member_data': member})
    # user_pk = request.session.get('user')

    # if user_pk:
    #     fuser =User.objects.get(pk = user_pk)
    #     return HTTPResponse(fuser.id)
    
    return render(request, "users/main.html",{'member_data': 'null'} )

@csrf_exempt
def login_view(request):
    if request.method == "GET":
        return render(request, "users/login.html")
    
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        res_data = {}
        user  = authenticate(username = username, password = password)

        if user is not None:
            member = User.objects.get(username=username)
            print("인증성공")
            login(request,user)
            request.session['user'] = member.id
            return redirect("users:main")

        else:
            res_data['error'] = "비밀번호가 일치하지 않습니다."
            print("인증실패")
    return render(request,"users/login.html", res_data)
    

def logout_view(request):
    request.session.flush()
    logout(request)
    return redirect("users:main")

@csrf_exempt
def signup_view(request):
    if request.method == "POST":
        print(111,request.POST)
        # profile_img = request.FILES["profile_img"]
        username = request.POST["username"]
        password = request.POST["password"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]
        student_id = request.POST["student_id"]

        user = User.objects.create_user(username,email,password)
        user.last_name = lastname
        user.first_name = firstname
        user.student_id = student_id
        # user.profile_img = profile_img
        user.save()

        return redirect("users:login")


    return render(request, "users/signup.html")

def index(request):
    boards = {'boards': Board.objects.all()}
    return render(request, 'users/list.html', boards)

def post(request):
    if not request.session.get('user'):
        return redirect("users:login")
    if request.method == "GET":
        board = Board()
        user_id = request.session['user']
        author = User.objects.get(pk = user_id)
    elif request.method == "POST":
        user_id = request.session['user']
        author = User.objects.get(pk = user_id)
        title = request.POST['title']
        content = request.POST['content']
        board = Board(author = author, title = title, content = content)
        board.save()

        return redirect("users:index")
    return render(request,'users/post.html', {'author' : author})

def detail(request, id):
    try:
        board = Board.objects.get(pk=id)
    except Board.DoesNotExist:
        raise Http404("Does not exist!")
    return render(request, 'users/detail.html', {'board': board})

@csrf_exempt
def delete(request,id):
    if not request.session.get('user'):
        return redirect("users:login")
    board = Board.objects.get(pk = id)
    board.delete()
    return redirect("users:index")

def edit(request,id):
    if not request.session.get('user'):
        return redirect("users:login")
    else:
        board = Board.objects.get(pk = id)
        if request.method == "POST":
            board.title = request.POST["title"]
            # board.author = request.POST["author"]
            board.content = request.POST["content"]

            board.save()

            return redirect("users:index")


    return render(request, 'users/edit.html', {'board' : board})

users/templates/users/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - {{ board.title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'users:index' %}" class="navbar-brand d-flex align-items-center">
                <strong>게시판</strong>
            </a>
        </div>
    </div>
</header>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ board.title }} - {{ board.author }}</h5>
            <p class="card-text"><small class="text-muted">{{ board.created_date | date:"Y-m-d h:i" }}</small></p>
            <p class="card-text">{{ board.content }}</p>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-auto mr-auto"></div>
        <div class="col-auto">
            <a class="btn btn-info" href="edit/{{ board.id }}" role="button">수정</a>
        </div>
        <div class="col-auto">
            <form id="delete-form" action="delete/{{ board.id }}" method="post">
                <input type="hidden" name="_method" value="delete"/>
                <button id="delete-btn" type="submit" class="btn btn-danger">삭제</button>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

users/templates/users/edit.html
<!-- {% load static %}
<form method="POST">
    {% csrf_token %}
    <h3>글 수정하기</h3>
    <input class="input_field" type="text" placeholder="글쓴이의 이름은?" name="author" value="{{ board.author }}"><br>
    <input class="input_field" type="text" placeholder="제목을 입력해주세요." name="title"  value="{{ board.title }}"><br>
    <input class="textarea_field" placeholder="내용을 입력해주세요." name="content" value = "{{board.content}}"><br>
        <div class="row">
            <div class="col-auto mr-auto"></div>
            <div class="col-auto">
                <input class="btn btn-primary" type="submit" role="button" value="글쓰기">
            </div>
        </div>
</form> -->

{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - 수정하기</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="/" class="navbar-brand d-flex align-items-center">
                <strong>수정하기</strong>
            </a>
        </div>
    </div>
</header>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="inputTitle" class="col-sm-2 col-form-label"><strong>제목</strong></label>
            <div class="col-sm-10">
                <input type="text" name="title" class="form-control" id="inputTitle" value="{{ board.title }}">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputAuthor" class="col-sm-2 col-form-label" ><strong>작성자</strong></label>
            <div class="col-sm-10">
                <input type="text" name="author" class="form-control" value="{{ board.author }}" id="inputAuthor">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputContent" class="col-sm-2 col-form-label"><strong>내용</strong></label>

            <div class="col-sm-10">
                <input type="text" name="content" class="form-control" id="inputContent"  value="{{ board.content }}">
            </div>
        </div>
        <div class="row">
            <div class="col-auto mr-auto"></div>
            <div class="col-auto">
                <input class="btn btn-primary" type="submit" role="button" value="수정하기">
            </div>
        </div>
    </form>
</div>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>

users/templates/users/list.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - 목록</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'users:index' %}" class="navbar-brand d-flex align-items-center">
                <strong>게시판</strong>
            </a>
        </div>
    </div>
</header>
<div class="container">
    <table class="table">
        <thead class="thead-light">
        <tr class="text-center">
            <th scope="col">#</th>
            <th scope="col">제목</th>
            <th scope="col">작성자</th>
            <th scope="col">작성일</th>
        </tr>
        </thead>
        <tbody>
        {% for board in boards %}
        <tr class="text-center">
            <th scope="row">
                <span>{{ board.id }}</span>
            </th>
            <td>
                <a href="post/{{ board.id }}">
                    <span>{{ board.title }}</span>
                </a>
            </td>
            <td>
                <span>{{ board.author }}</span>
            </td>
            <td>
                <span>{{ board.created_date | date:"Y-m-d h:i" }}</span>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <div class="col-auto mr-auto"></div>
        <div class="col-auto">
            <a class="btn btn-primary" href="{% url 'users:post' %}" role="button">글쓰기</a>
        </div>
    </div>
</div>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<title>Login V2</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href='{% static "images/icons/favicon.ico" %}'/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "fonts/iconic/css/material-design-iconic-font.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/animate/animate.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/css-hamburgers/hamburgers.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/animsition/css/animsition.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/select2/select2.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/daterangepicker/daterangepicker.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "css/util.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}'>
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form action = "" method = "post"class="login100-form validate-form">
					{%csrf_token %}
					<span class="login100-form-title p-b-26">
						환영합니다
						<!-- {{res_data}} -->
					</span>
					<span class="login100-form-title p-b-48">
{#						<i class="zmdi zmdi-font"></i>#}
                        <img src="https://ww.namu.la/s/452135c0507972ac84a1280a7830b665310aa8897090d235be7017e96a666979de058d542893689518a700f8631b368c86467ce37b7d9235e24e61de3e67704c9ede04b4174b9edec93590008ae22984" height="100px">
					</span>

					<div class="wrap-input100 validate-input" >
						<input class="input100" type="text" name="username">
						<span class="focus-input100" data-placeholder="username"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password">
						<span class="focus-input100" data-placeholder="Password"></span>
					</div>
					
					<input type = "submit" value = "로그인">
					<!-- <div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Login
							</button>
						</div>
					</div> -->

					<div class="text-center p-t-115">
						<span class="txt1">
							계정이 없으십니까?
						</span>

						<a class="txt2" href="{% url 'users:signup' %}">
							회원 가입
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src='{% static "vendor/jquery/jquery-3.2.1.min.js" %}' ></script>
<!--===============================================================================================-->
	<script src='{% static "vendor/animsition/js/animsition.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "vendor/bootstrap/js/popper.js" %}'></script>
	<script src='{% static "vendor/bootstrap/js/bootstrap.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "vendor/select2/select2.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "vendor/daterangepicker/moment.min.js" %}'></script>
	<script src='{% static "vendor/daterangepicker/daterangepicker.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "vendor/countdowntime/countdowntime.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "js/main.js" %}'></script>

</body>
</html>

users/templates/users/login12.html
{% load static %}

로그인 페이지
<br>

<img src = "{% static '/assets/female7.jpg' %}" alt = "">
<br>

{{res_data}}

{% if user.is_authenticated %}
    로그인성공!
    {{user.username}} 님 환영합니다.
    <!-- {{user.profile_img.url}} -->
    <!-- <img src = "{{ user.profile_img.url }}" alt ="프로필사진"> -->
    <a href= "{% url 'users:logout' %}">로그아웃</a>
    <a href= "{% url 'users:main' %}">메인으로가기</a>


{% else %}

<form action = "" method = "post">
    {%csrf_token %}
    <input name = "username" type = "text">
    <input name = "password" type = "password">
    <input type = "submit" value = "로그인">

</form>
<a href = "{% url 'users:signup' %}"> 회원가입 </a>
<a href= "{% url 'users:main' %}">메인으로가기</a>


{% endif %}

users/templates/users/post.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판 - 글쓰기</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm mb-3">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'users:index' %}" class="navbar-brand d-flex align-items-center">
                <strong>게시판</strong>
            </a>
        </div>
    </div>
</header>
<div class="container">
    <form action="/auth/post" method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="inputTitle" class="col-sm-2 col-form-label"><strong>제목</strong></label>
            <div class="col-sm-10">
                <input type="text" name="title" class="form-control" id="inputTitle">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputAuthor" class="col-sm-2 col-form-label"><strong>작성자</strong></label>
            <div class="col-sm-10">
                <input name="author" class="form-control" id="inputAuthor" data-placeholder={{author}}>
            </div>
        </div>
        <div class="form-group row">
            <label for="inputContent" class="col-sm-2 col-form-label"><strong>내용</strong></label>
            <div class="col-sm-10">
                <textarea type="text" name="content" class="form-control" id="inputContent"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-auto mr-auto"></div>
            <div class="col-auto">
                <input class="btn btn-primary" type="submit" role="button" value="글쓰기">
            </div>
        </div>
    </form>
</div>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>

users/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Login V2</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href='{% static "assets/img/favicon.ico" %}'/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}'>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href='{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}'>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href='{% static "fonts/iconic/css/material-design-iconic-font.min.css" %}'>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href='{% static "vendor/animate/animate.css" %}'>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href='{% static "vendor/css-hamburgers/hamburgers.min.css" %}'>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href='{% static "vendor/animsition/css/animsition.min.css" %}'>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href='{% static "vendor/select2/select2.min.css" %}'>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href='{% static "vendor/daterangepicker/daterangepicker.css" %}'>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href='{% static "css/util.css" %}'>
    <link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}'>
    <!--===============================================================================================-->
</head>
<body>
    <!-- <form action = "" method = "POST" enctype="multipart/form-data"> -->
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <form afction = "" method = "POST" enctype = "multipart/form-data" class="login100-form validate-form">
					<span class="login100-form-title p-b-26">
						회원 가입
					</span>
                <span class="login100-form-title p-b-48">
<!-- {#						<i class="zmdi zmdi-font"></i>#} -->
                        <img src="https://ww.namu.la/s/452135c0507972ac84a1280a7830b665310aa8897090d235be7017e96a666979de058d542893689518a700f8631b368c86467ce37b7d9235e24e61de3e67704c9ede04b4174b9edec93590008ae22984"
                             height="100px">
					</span>

                <div class="wrap-input100 validate-input" data-validate="Valid email is: a@b.c">
                    <input class="input100" type="text" name="email">
                    <span class="focus-input100" data-placeholder="Email"></span>
                </div>

                <div class="wrap-input100 validate-input" >
                    <input class="input100" type="text" name="username">
                    <span class="focus-input100" data-placeholder="username"></span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
                    <input class="input100" type="password" name="password">
                    <span class="focus-input100" data-placeholder="Password"></span>
                </div>

                <div class="wrap-input100">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
                    <input class="input100"  name="lastname">
                    <span class="focus-input100" data-placeholder="Last Name"></span>
                </div>

                <div class="wrap-input100">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
                    <input class="input100"  name="firstname">
                    <span class="focus-input100" data-placeholder="First Name"></span>
                </div>

                <div class="wrap-input100">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
                    <input class="input100"  name="student_id">
                    <span class="focus-input100" data-placeholder="Student-Id"></span>
                </div>

                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button class="login100-form-btn">
                            가입
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src='{% static "vendor/jquery/jquery-3.2.1.min.js" %}'></script>
<!--===============================================================================================-->
<script src='{% static "vendor/animsition/js/animsition.min.js" %}'></script>
<!--===============================================================================================-->
<script src='{% static "vendor/bootstrap/js/popper.js" %}'></script>
<script src='{% static "vendor/bootstrap/js/bootstrap.min.js" %}'></script>
<!--===============================================================================================-->
<script src='{% static "vendor/select2/select2.min.js" %}'></script>
<!--===============================================================================================-->
<script src='{% static "vendor/daterangepicker/moment.min.js" %}'></script>
<script src='{% static "vendor/daterangepicker/daterangepicker.js" %}'></script>
<!--===============================================================================================-->
<script src='{% static "vendor/countdowntime/countdowntime.js" %}'></script>
<!--===============================================================================================-->
<script src='{% static "js/main.js" %}'></script>

</body>
</html>

users/templates/users/signup12.html
{% load static %}
<link rel = "stylesheet" href = "{% static 'signup.css' %}">
회원가입 페이지
<!-- br-줄바꿈 -->
<br> 
<img src = "{% static '/assets/female15.jpg' %}" alt = "">

<form action = "" method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>아이디</p>
    <input name = "username" type= "text">
    <p>비밀번호</P>
    <input name = "password" type= "password">
    <p>성</p>
    <input name = "firstname" type= "text">
    <p>이름</p>
    <input name = "lastname" type= "text">
    <p>이메일</p>
    <input name = "email" type = "text">
    <p>학번</p>
    <input name = "student_id" type = "text">
    <p>프로필사진</p>
    <input name = "profile_img" type = "file">
    <p></p>
    <input type = "submit", value = "회원가입">
    

</form>